#!/usr/bin/env python3
"""jsonfilter 桩：只实现 init.d 用到的 @.days[@.date='D'].isOffDay。"""
import json, os, re, sys
if os.environ.get("FAKE_JSONFILTER") == "off": sys.exit(127)
f = expr = None
argv = sys.argv[1:]
i = 0
while i < len(argv):
    if argv[i] == "-i": f = argv[i+1]; i += 2
    elif argv[i] == "-e": expr = argv[i+1]; i += 2
    else: i += 1
m = re.match(r"@\.days\[@\.date='([^']*)'\]\.isOffDay$", expr or "")
if not m or not f: sys.exit(2)
try:
    data = json.load(open(f))
except Exception:
    sys.exit(2)
for day in data.get("days", []):
    if day.get("date") == m.group(1):
        print("true" if day.get("isOffDay") else "false")
        sys.exit(0)
sys.exit(2)
